//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studiotaiha.Hanbura.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studiotaiha.Hanbura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   汎ぶら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダイアログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   等倍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DotByDot {
            get {
                return ResourceManager.GetString("DotByDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExceptionInformation {
            get {
                return ResourceManager.GetString("ExceptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   倍率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   常に手前に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Settings_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートを自動で確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CheckForUpdateAutomatically {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdateAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了時に確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ConfirmShutdown {
            get {
                return ResourceManager.GetString("Settings_ConfirmShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   子ウィンドウの追従を有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_EnableChildWindowsTracking {
            get {
                return ResourceManager.GetString("Settings_EnableChildWindowsTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   子ウィンドウが画面外にでないようにする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PreventChildWindowsOutOfScreen {
            get {
                return ResourceManager.GetString("Settings_PreventChildWindowsOutOfScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前回終了時の位置を記憶する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_RestorePosition {
            get {
                return ResourceManager.GetString("Settings_RestorePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前回終了時のサイズを復元する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_RestoreSize {
            get {
                return ResourceManager.GetString("Settings_RestoreSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作のヒントを表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowToolTip {
            get {
                return ResourceManager.GetString("Settings_ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示倍率を変更します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Scale {
            get {
                return ResourceManager.GetString("ToolTip_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウを常に手前に表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_AlwaysOnTop {
            get {
                return ResourceManager.GetString("ToolTip_Settings_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   汎ブラ起動時にアップデートの有無を自動で確認します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_CheckForUpdateAutomatically {
            get {
                return ResourceManager.GetString("ToolTip_Settings_CheckForUpdateAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   汎ブラの終了時に確認ダイアログを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_ConfirmShutdown {
            get {
                return ResourceManager.GetString("ToolTip_Settings_ConfirmShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メインウィンドウを動かしたとき、子ウィンドウがそれに追従して動きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_EnableChildWindowsTracking {
            get {
                return ResourceManager.GetString("ToolTip_Settings_EnableChildWindowsTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   子ウィンドウが画面の外に移動して操作ができなくなることを防ぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_PreventChildWindowsOutOfScreen {
            get {
                return ResourceManager.GetString("ToolTip_Settings_PreventChildWindowsOutOfScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時に、前回終了時のウィンドウ位置を復元します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_RestorePosition {
            get {
                return ResourceManager.GetString("ToolTip_Settings_RestorePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時に、前回終了時のウィンドウサイズを復元します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_RestoreSize {
            get {
                return ResourceManager.GetString("ToolTip_Settings_RestoreSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタンなどにマウスを載せたとき操作のヒントを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Settings_ShowToolTip {
            get {
                return ResourceManager.GetString("ToolTip_Settings_ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
